
@server=https://riz-inno-sbx-cds-bug-3-srv.cfapps.us10.hana.ondemand.com

###
{{server}}/synch/Synchs

###
POST {{server}}/synch/startSynch
Content-Type: application/json

{
    "srcDestinationName": "sf-inno-api",
    "transferEntityName": "User"
}